name: npm-cache-restore-save
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-beta-node-
      - name: NPM install
        shell: bash
        run: |
          pwd
          npm install
      - uses: actions/cache/save@v3
        if: ${{ steps.cache-restore.outputs.cache-primary-key != steps.cache-restore.outputs.cache-matched-key }}
        id: cache-save
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
