name: npm-cache-save-restore
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM install
        shell: bash
        run: |
          pwd
          npm install
      - uses: actions/cache/save@v3
        id: cache-save
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-beta-node-
      - name: Fail if cache not found
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss occurred, hence throwing error."
          exit 1
